import type { Metadata } from 'next';
import Provider from './_trpc/Provider';
import './globals.css';
import { poppins, spaceMano, jetMono } from './styles/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${spaceMano.variable} ${poppins.variable} antialiased ${poppins.className} ${jetMono.variable}`}>
                <div className="w-full ">
                    <Provider>{children}</Provider>
                </div>
            </body>
        </html>
    );
}
